language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install --global yarn --cache-min 999999999
install:
  - npm install
script:
  - ./scripts/lint.sh
  - ./scripts/build.sh
  - ./scripts/push-precompiled.sh

