language: node_js
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
os:
  - linux
  - osx
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install --global yarn --cache-min 999999999
install:
  - npm install
script:
  - export VERSION=$(node -p "require('./package.json').version")
  - ./scripts/lint.sh
  - ./scripts/test.sh
  - ./scripts/build.sh
  - npm run release --linux
